name: Tests
on: push
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:16.3.0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Spago install
        run: npx spago -x test.dhall install
      - name: Spago build
        run: npx spago -x test.dhall build
      - name: Spago test
        run: npm test
