name: Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Spago install
        run: npx spago -x test.dhall install
      - name: Spago build
        run: npx spago -x test.dhall build
      - name: Spago test
        run: npm test
